### PR TITLE
Qc plus

### PR DESCRIPTION
**Pull request by mairi-mcclean**

### CODE REVIEW

**Review by cartal — APPROVED** [review]

**Comment by mairi-mcclean** [comment]
Hi! So I've been looking into how to retroactively sign and push commits, and I thought I found a solution. However, it runs into problems with some of the commits you made to the main branch, so I think it would be best if we could go through this together when you get back? I'm scared of making an error and doing some real damage to the repo.

Thanks!

**Comment by mairi-mcclean** [comment]
So I think I made a mistake when trying to retroactively sign the commits... Could we go through this when you get back, please? I'm concerned about making any major changes that might result in permanent issues with the repo, but I also would like to keep working on it.

Thanks!

**Comment by mairi-mcclean** [comment]
So I think I made a mistake when trying to retroactively sign the commits... Could we go through this when you get back, please? I'm concerned about making any major changes that might result in permanent issues with the repo, but I also would like to keep working on it.

Thanks!

**Comment by mairi-mcclean** [comment]
So I think I made a mistake when trying to retroactively sign the commits... Could we go through this when you get back, please? I'm concerned about making any major changes that might result in permanent issues with the repo.

Thanks!

**Pull request closed without merging**
